### ISSUE TITLE
Mike Amundson's 'HAL Forms' draft

### ISSUE THREAD

**Issue by agebhar1** [Dwolla/hal-forms#6]
I stumbled upon your 'hal-forms' draft, maybe align with/mention [Mike Amundson]'s draft on the same issue?

[Mike Amundson]: https://github.com/mamund/hal-forms

**Comment by pezra** [comment]
Unfortunately, Mike's approach to forms is completely different than this one. I don't see a way to unify such disparate approaches.

From my perspective, this approach seems more HAL-like. Mike's approach is to layer form semantics onto regular links in HAL documents. I see the appeal of that but it seems a little too meta for a format whose whole reason for existence is simplicity and pragmatism. This approach puts the form front and center and is simple enough that even simple clients should be able to implement it.
