### ISSUE TITLE
expand and clarify field type

### ISSUE THREAD

**Issue by pezra** [Dwolla/hal-forms#8]
## Expansion

There are a few more field types that would be widely useful. I suggest
 - `hidden` - fields that must be in the submission but are immutable and provide no useful information to the user
 - `time` - fields representing just the time of day
 - `datetime` - fields have a date and time component
 - `text` - fields that are expected to contain large amounts of text
 
## Clarification

Make the fact that `type` is a hint more prominent and point out that clients should treat unrecognized types as `string`.

**Comment by jareddellitt** [comment]
Hey @pezra, sorry for the delayed response. Yes, PRs are welcome!
